# -*- coding: utf-8 -*-
"""teste2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhkr25mey31NMKp0syb3xgYjvsaPwfqz
"""

import streamlit as st
from streamlit_folium import folium_static
import folium
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# Mapa base com marcadores
m = folium.Map(location=[-25.426372, -49.307217], zoom_start=12)

# Lista de locais turísticos
locais = [
    ("Ópera de Arame", -25.384618, -49.276169, 'gray'),
    ("Jardim Botânico", -25.443083, -49.238214, 'green'),
    ("Parque Tanguá", -25.379066, -49.282423, 'green'),
    ("Museu Oscar Niemeyer", -25.410112, -49.26723, 'blue'),
    ("Parque Barigui", -25.426372, -49.307217, 'green'),
    ("Santa Felicidade", -25.400817, -49.334319, 'orange'),
    ("Bosque do Alemão", -25.404467, -49.288117, 'green'),
    ("Feira do Largo da Ordem", -25.427692, -49.273755, 'red'),
    ("Memorial da Segurança no Transporte", -25.452439, -49.364862, 'blue'),
    ("Shopping Pátio Batel", -25.44293, -49.290818, 'black'),
    ("Ligga Arena", -25.448305, -49.276924, 'pink'),
    ("Museu de Arte Indígena", -25.454071, -49.285374, 'blue'),
    ("Memorial Ucraniano", -25.402374, -49.304958, 'purple'),
    ("Shopping Estação", -25.43816, -49.267398, 'black'),
    ("Museu do Holocausto de Curitiba", -25.415166, -49.272559, 'blue'),
]

for nome, lat, lon, cor in locais:
    folium.Marker(
        location=[lat, lon],
        popup=nome,
        icon=folium.Icon(color=cor, icon='star')
    ).add_to(m)

# Função para criar legenda
def criar_legenda():
    patches = [
        mpatches.Patch(color='green', label='Parques/Jardins'),
        mpatches.Patch(color='blue', label='Museus'),
        mpatches.Patch(color='red', label='Feiras'),
        mpatches.Patch(color='orange', label='Bairros'),
        mpatches.Patch(color='gray', label='Teatros'),
        mpatches.Patch(color='black', label='Shopping'),
        mpatches.Patch(color='pink', label='Arena e estádios'),
        mpatches.Patch(color='purple', label='Locais históricos'),
    ]
    fig, ax = plt.subplots(figsize=(8, 2))
    ax.legend(handles=patches, loc='center', ncol=4, frameon=False)
    ax.axis('off')
    return fig

# Configuração da página
PAGE_CONFIG = {"page_title": "Aplicação de Mapas", "page_icon": ":smiley:", "layout": "centered"}
st.set_page_config(**PAGE_CONFIG)

def main():
    st.title("Mapa de Curitiba para rotas turísticas")
    menu = ["Home", "Mapa", "Faça sua rota"]
    choice = st.sidebar.selectbox("Menu", menu)

    if choice == 'Home':
        st.text("Planejar sua viagem ficou muito mais fácil e prático.")
        st.text("Nosso aplicativo foi criado especialmente para apoiar você, turista, na organização de roteiros e na descoberta das melhores experiências que Curitiba tem a oferecer. Aqui, você encontra os 15 principais pontos turísticos da cidade, cuidadosamente selecionados com base no ranking do TripAdvisor, garantindo que você visite os locais mais bem avaliados e imperdíveis. Explore rotas personalizadas, monte seu próprio itinerário e aproveite cada momento na capital ecológica do Brasil com tranquilidade e segurança.")
        st.text("Curitiba te espera. E a gente te ajuda a chegar lá.")

    elif choice == 'Mapa':
        st.subheader("Visualizar Mapa")
        folium_static(m)

        st.subheader("Legenda")
        fig = criar_legenda()
        st.pyplot(fig)

    else:
        st.subheader("Funcionalidade em construção.")

if __name__ == "__main__":
    main()